/**
 *   TokenKind is a simple enumeration of the different kinds of tokens
 *   
 */
package miniJava.SyntacticAnalyzer;

public enum TokenKind {NUM, PLUS, TIMES, LPAREN, RPAREN, EOT, ERROR, MINUS, DIVIDE, SEMICOLON, PERIOD, GREATER, LESS, EQUALS, LESSOREQ, GREATOREQ, NOTEQ, 
	

AND, OR, NOT, CLASS, IF, WHILE, RETURN, ELSE, NEW, THIS, VOID, INT, BOOLEAN, ID, ASSIGN, PUBLIC, PRIVATE, STATIC, LCURBRACK, RCURBRACK, LSQUBRACK,

RSQUBRACK, COMMA, TRUE, FALSE, LINECOMMENT, PARACOMMENT, NULL} 
